Improve Salt Bundle promote pipeline
openSUSE/salt-package-promote-obs pull request #30
Opened 2023-06-20 14:18 UTC by ycedres

This PR fixes the part of https://github.com/SUSE/spacewalk/issues/21338 regarding improvements for the Salt Bundle promote pipeline. 

**Previous behaviour**
Run one `osc copypac` for every dependency package and something similar for subproject configurations. Every new dependency or subproject has to be manually included.
**From now on**
The list of packages and subprojects is retrieved from OBS and the copies are generated dinamycally.

2023-06-21 08:04 UTC, ycedres commented
I believe we could do something similar for the other pipeline, however I've noticed there that not all packages are copied but just a subset and I'm not sure why.

2023-06-26 09:14 UTC, meaksh requested changes
Thanks for the PR. I just left some comments.

BTW, are you planning to push the changes for the classic Salt package pipeline on this same PR or in a differnt one?

2023-06-26 09:16 UTC, ycedres commented on promote_salt_bundle_packages.py
> +import pdb; pdb.set_trace()
For sure 😅

2023-06-26 09:43 UTC, ycedres commented on promote_salt_bundle_packages.py
> +        if package_name is not None and not has_link(client, src, package_name):
I added your suggested comments and also a header comment.

2023-06-26 09:49 UTC, ycedres commented
> Thanks for the PR. I just left some comments.
> 
> BTW, are you planning to push the changes for the classic Salt package pipeline on this same PR or in a differnt one?

I'd like to push the changes for the classic Salt in a different PR, as I'd like to try this change first and see how it goes.

2023-06-26 10:15 UTC, meaksh approved these changes
LGTM - keep in mind this would require we add `osctiny` as installed package in our Jenkins workers (sumadocker hosts).

We would need to add this new package to these instances via our infrastructure repo, but I just noticed it is already there: https://gitlab.suse.de/galaxy/infrastructure/-/blob/master/srv/salt/jenkins-node/base.sls#L46

So, in principle, we are good to go.

2023-06-26 10:59 UTC, merged

2023-06-26 11:27 UTC, meaksh commented
As mentioned in Slack, we just realized this PR is missing showing the "diff" for the project configs.

A new PR will come shortly to including this changes too.